name: deploy docs

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  deployments: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Deploy documentation
        run: |
          pip install mkdocs-material
          pip install mkdocs-mermaid2-plugin
          mkdocs gh-deploy --force
